{% set version = "1.3.7" %}

package:
  name: hs_restclient
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/hs_restclient/hs_restclient-{{ version }}.tar.gz
  sha256: 313c5905220bfb659db0fc188b00e65b2094e92b9a7fc91ed7824aa9aae3b2cd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - oauthlib
    - requests
    - requests-oauthlib
    - requests-toolbelt

test:
  requires:
    - python {{ python_min }}
  imports:
    - hs_restclient
    - hs_restclient.endpoints

about:
  home: https://pypi.org/project/hs_restclient/
  summary: HydroShare REST API client library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
