{% set version = "1.3.6" %}

package:
  name: hs_restclient
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hs_restclient/hs_restclient-{{ version }}.tar.gz
  sha256: 44775582b41170717e08247398e4478fd088deb85e1efd1a0d8d58bd2112afdc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - oauthlib
    - requests
    - requests-oauthlib
    - requests-toolbelt

test:
  imports:
    - hs_restclient
    - hs_restclient.endpoints

about:
  home: https://pypi.org/project/hs_restclient/
  summary: HydroShare REST API client library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
