travis:
  secure:
    BINSTAR_TOKEN: d2/VZhTH4ffniFEQOl5/ADORxre4chtoQbz5wII0AqumzOwQGOAMuDn7M6t23ECdU7xziy+cNLeL8HJ6GBt4OkRqoBRvsUoPdxiNMBTUPUyjUJ1iwDCERFNvlBJLmsTsNpfFfVjx1s039s/TTNvwzrDTuhKQtUmq4vfVe4O2GQdmdq3NR7//ZPLJk1cbRmwWyk3sFLV4H5wwZqQazLrrykOXLYmYdpE6G9XyK79DGWACTAf6KbaziDD/k7xWOwcYRPHO7gAQiHePZZpOEMd4zgnonYB9LE3JmkRx+38tXxkh4XGnXI4NClBpGXHc/uTDeCpC4JUcjLXaEEpYX52W7ZQmXO8/e5givDKnd9tRWsZBUiD5yuz0S71Q7Pa2YxDctm6dH7DW6qyOgeFx6U8xvei6Wg3FvKuEvGB3NmrUU6G+MsR3KmBtWEf1TEVEznCDirwoFehgJjhmOvj2OHpwxOWmpOkLPyYCOml9LeyFqxVf699S9Sq1Kmv52O5CjI0sIixol9ZmrOaaVcEKETzpszBO4+7YKXO2UOWJNTpM3rdJiQ85z2oV2TC7RDKx1nmw4sxJcqVBfuf72pi6LpgIb5DtZFDlSM0m5ko26As+37GWbHtcbh/3e1EukDtaoeyfl3iIyGnHGDIiyP+/COkZbID4CeZI6e13cPWW+e27sXA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
